version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PaSsWoRd
    ports:
      - "1433:1433"
    volumes:
      - mssql_db_volume:/var/opt/mssql
    networks:
      - app-network
volumes:
  mssql_db_volume:
  app_volume:
networks:
  app-network:
    driver: bridge
