server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8080

spring:
  profiles:
    active: dev
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    sqlMigrationSuffix: .sql
    validateOnMigrate: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=TechStore;encrypt=true;trustServerCertificate=true
    username: sa
    password: Rintuna2808
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://tech_store_db;database=TechStore
    username: sa
    password: Rintuna2808
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl