-- CREATE USER TABLE
CREATE TABLE USERS
(
    USER_ID    VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    USER_NAME  VARCHAR(255) NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL,
    CART_ID    VARCHAR(255),
    POINT      FLOAT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX USER_ID_INDEX ON USERS (USER_ID);

-- CREATE ROLE TABLE
CREATE TABLE ROLES
(
    ROLE_ID          VARCHAR(255) NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255),
    ROLE_NAME        VARCHAR(255) NOT NULL,
    CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ROLE_ID)
);
CREATE UNIQUE INDEX ROLE_ID_INDEX ON ROLES (ROLE_ID);


-- CREATE USERS-ROLES MAPPING TABLE
CREATE TABLE USERS_ROLES
(
    USER_ID    VARCHAR(255) NOT NULL,
    ROLE_ID    VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX USER_FK_INDEX ON USERS_ROLES (USER_ID);
CREATE INDEX ROLE_FK_INDEX ON USERS_ROLES (ROLE_ID);

-- create cart table
CREATE TABLE CART
(
    CART_ID     VARCHAR(255) NOT NULL,
    TOTAL_PRICE FLOAT        NOT NULL,
    USER_NAME   VARCHAR(255) NOT NULL,
    PRIMARY KEY (CART_ID)
);

-- create cart item table
CREATE TABLE CART_ITEM
(
    CART_ITEM_ID VARCHAR(255) NOT NULL,
    PRICE        FLOAT        NOT NULL,
    PRODUCT_ID   VARCHAR(255),
    QUANTITY     INTEGER      NOT NULL,
    CART_ID      VARCHAR(255),
    PRIMARY KEY (CART_ITEM_ID),
    CONSTRAINT CART_FK FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- create order table
CREATE TABLE ORDER_TABLE
(
    ORDER_ID          VARCHAR(255) NOT NULL,
    TOTAL_ORDER_PRICE FLOAT        NOT NULL,
    USER_NAME         VARCHAR(255) NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

-- create order item table
CREATE TABLE ORDER_ITEM
(
    ORDER_ITEM_ID    VARCHAR(255) NOT NULL,
    ORDER_ITEM_PRICE FLOAT        NOT NULL,
    PRODUCT_ID       VARCHAR(255) NOT NULL,
    QUANTITY         INTEGER      NOT NULL,
    ORDER_ID         VARCHAR(255) NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE (ORDER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
